name: Deploy GitHub Pages

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - source
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: BeforeScript
        run: |
          git config --global user.name "zhanglun"
          git config --global user.email "zhanglun1410@gmail.com"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Node Enviroment
        uses: actions/setup-node@v3
        with:
          node-version: '17'

      - name: Install Dependenices
        run: yarn install
        run: yarn run download
        run: npx gatsby clean
        run: npm cache clean --force

      - name: Build
        run: |
          echo "Starting building..."
          npm run build
          npm run build-storybook
          cp ./CNAME ./public/CNAME
          cp ./ads.txt ./public/ads.txt

      # 部署到 GitHub Pages
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.gatsbyDeploy }}
          BRANCH: gh-pages
          FOLDER: public

